<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ESconto extends \ESconto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'beneficiario' => [parent::class, 'beneficiario', null],
        "\0".parent::class."\0".'codice_sconto' => [parent::class, 'codice_sconto', null],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null],
        "\0".parent::class."\0".'ordine' => [parent::class, 'ordine', null],
        "\0".parent::class."\0".'valore_sconto' => [parent::class, 'valore_sconto', null],
        'beneficiario' => [parent::class, 'beneficiario', null],
        'codice_sconto' => [parent::class, 'codice_sconto', null],
        'is_active' => [parent::class, 'is_active', null],
        'ordine' => [parent::class, 'ordine', null],
        'valore_sconto' => [parent::class, 'valore_sconto', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
