<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ESegnalazione extends \ESegnalazione implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id_segnalazione' => [parent::class, 'id_segnalazione', null],
        "\0".parent::class."\0".'recensione_segnalata' => [parent::class, 'recensione_segnalata', null],
        "\0".parent::class."\0".'testo' => [parent::class, 'testo', null],
        "\0".parent::class."\0".'utente' => [parent::class, 'utente', null],
        'id_segnalazione' => [parent::class, 'id_segnalazione', null],
        'recensione_segnalata' => [parent::class, 'recensione_segnalata', null],
        'testo' => [parent::class, 'testo', null],
        'utente' => [parent::class, 'utente', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
