<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EIndirizzo extends \EIndirizzo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cap' => [parent::class, 'cap', null],
        "\0".parent::class."\0".'cliente_residente' => [parent::class, 'cliente_residente', null],
        "\0".parent::class."\0".'indirizzo' => [parent::class, 'indirizzo', null],
        "\0".parent::class."\0".'is_deleted' => [parent::class, 'is_deleted', null],
        "\0".parent::class."\0".'ordini' => [parent::class, 'ordini', null],
        'cap' => [parent::class, 'cap', null],
        'cliente_residente' => [parent::class, 'cliente_residente', null],
        'indirizzo' => [parent::class, 'indirizzo', null],
        'is_deleted' => [parent::class, 'is_deleted', null],
        'ordini' => [parent::class, 'ordini', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
