<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EChefRicetta extends \EChefRicetta implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chef_id' => [parent::class, 'chef_id', null],
        "\0".parent::class."\0".'data_pubblicazione' => [parent::class, 'data_pubblicazione', null],
        "\0".parent::class."\0".'ricetta_id' => [parent::class, 'ricetta_id', null],
        'chef_id' => [parent::class, 'chef_id', null],
        'data_pubblicazione' => [parent::class, 'data_pubblicazione', null],
        'ricetta_id' => [parent::class, 'ricetta_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
