<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ECliente extends \ECliente implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carte_di_credito' => [parent::class, 'carte_di_credito', null],
        "\0".parent::class."\0".'cellulare' => [parent::class, 'cellulare', null],
        "\0".parent::class."\0".'cognome' => [parent::class, 'cognome', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id_cliente' => [parent::class, 'id_cliente', null],
        "\0".parent::class."\0".'indirizzi' => [parent::class, 'indirizzi', null],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null],
        "\0".parent::class."\0".'ordini' => [parent::class, 'ordini', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'punti_fedelta' => [parent::class, 'punti_fedelta', null],
        "\0".parent::class."\0".'recensioni' => [parent::class, 'recensioni', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'sconti' => [parent::class, 'sconti', null],
        "\0".parent::class."\0".'segnalazioni' => [parent::class, 'segnalazioni', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'carte_di_credito' => [parent::class, 'carte_di_credito', null],
        'cellulare' => [parent::class, 'cellulare', null],
        'cognome' => [parent::class, 'cognome', null],
        'email' => [parent::class, 'email', null],
        'id_cliente' => [parent::class, 'id_cliente', null],
        'indirizzi' => [parent::class, 'indirizzi', null],
        'nome' => [parent::class, 'nome', null],
        'ordini' => [parent::class, 'ordini', null],
        'password' => [parent::class, 'password', null],
        'punti_fedelta' => [parent::class, 'punti_fedelta', null],
        'recensioni' => [parent::class, 'recensioni', null],
        'roles' => [parent::class, 'roles', null],
        'sconti' => [parent::class, 'sconti', null],
        'segnalazioni' => [parent::class, 'segnalazioni', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
