<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EOrdine extends \EOrdine implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carta_ordine' => [parent::class, 'carta_ordine', null],
        "\0".parent::class."\0".'cliente' => [parent::class, 'cliente', null],
        "\0".parent::class."\0".'codice_sconto' => [parent::class, 'codice_sconto', null],
        "\0".parent::class."\0".'data_ordine' => [parent::class, 'data_ordine', null],
        "\0".parent::class."\0".'id_ordine' => [parent::class, 'id_ordine', null],
        "\0".parent::class."\0".'importo_ordine' => [parent::class, 'importo_ordine', null],
        "\0".parent::class."\0".'indirizzo_spedizione' => [parent::class, 'indirizzo_spedizione', null],
        "\0".parent::class."\0".'punti_fedelta_guadagnati' => [parent::class, 'punti_fedelta_guadagnati', null],
        "\0".parent::class."\0".'q_prodotto_ordine' => [parent::class, 'q_prodotto_ordine', null],
        "\0".parent::class."\0".'quantita_tot_prodotti' => [parent::class, 'quantita_tot_prodotti', null],
        "\0".parent::class."\0".'stato_ordine' => [parent::class, 'stato_ordine', null],
        'carta_ordine' => [parent::class, 'carta_ordine', null],
        'cliente' => [parent::class, 'cliente', null],
        'codice_sconto' => [parent::class, 'codice_sconto', null],
        'data_ordine' => [parent::class, 'data_ordine', null],
        'id_ordine' => [parent::class, 'id_ordine', null],
        'importo_ordine' => [parent::class, 'importo_ordine', null],
        'indirizzo_spedizione' => [parent::class, 'indirizzo_spedizione', null],
        'punti_fedelta_guadagnati' => [parent::class, 'punti_fedelta_guadagnati', null],
        'q_prodotto_ordine' => [parent::class, 'q_prodotto_ordine', null],
        'quantita_tot_prodotti' => [parent::class, 'quantita_tot_prodotti', null],
        'stato_ordine' => [parent::class, 'stato_ordine', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
