<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EProdotto extends \EProdotto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descrizione' => [parent::class, 'descrizione', null],
        "\0".parent::class."\0".'id_prodotto' => [parent::class, 'id_prodotto', null],
        "\0".parent::class."\0".'immagini' => [parent::class, 'immagini', null],
        "\0".parent::class."\0".'ingredienti' => [parent::class, 'ingredienti', null],
        "\0".parent::class."\0".'is_gluten_free' => [parent::class, 'is_gluten_free', null],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null],
        "\0".parent::class."\0".'nome_categoria' => [parent::class, 'nome_categoria', null],
        "\0".parent::class."\0".'prezzo' => [parent::class, 'prezzo', null],
        "\0".parent::class."\0".'punti_fedelta' => [parent::class, 'punti_fedelta', null],
        "\0".parent::class."\0".'q_prodotto_ordine' => [parent::class, 'q_prodotto_ordine', null],
        "\0".parent::class."\0".'quantita_disp' => [parent::class, 'quantita_disp', null],
        "\0".parent::class."\0".'recensioni' => [parent::class, 'recensioni', null],
        'descrizione' => [parent::class, 'descrizione', null],
        'id_prodotto' => [parent::class, 'id_prodotto', null],
        'immagini' => [parent::class, 'immagini', null],
        'ingredienti' => [parent::class, 'ingredienti', null],
        'is_gluten_free' => [parent::class, 'is_gluten_free', null],
        'nome' => [parent::class, 'nome', null],
        'nome_categoria' => [parent::class, 'nome_categoria', null],
        'prezzo' => [parent::class, 'prezzo', null],
        'punti_fedelta' => [parent::class, 'punti_fedelta', null],
        'q_prodotto_ordine' => [parent::class, 'q_prodotto_ordine', null],
        'quantita_disp' => [parent::class, 'quantita_disp', null],
        'recensioni' => [parent::class, 'recensioni', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
