<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ERecensione extends \ERecensione implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cliente' => [parent::class, 'cliente', null],
        "\0".parent::class."\0".'id_recensione' => [parent::class, 'id_recensione', null],
        "\0".parent::class."\0".'prodotto' => [parent::class, 'prodotto', null],
        "\0".parent::class."\0".'segnalazioni' => [parent::class, 'segnalazioni', null],
        "\0".parent::class."\0".'testo' => [parent::class, 'testo', null],
        "\0".parent::class."\0".'valutazione' => [parent::class, 'valutazione', null],
        'cliente' => [parent::class, 'cliente', null],
        'id_recensione' => [parent::class, 'id_recensione', null],
        'prodotto' => [parent::class, 'prodotto', null],
        'segnalazioni' => [parent::class, 'segnalazioni', null],
        'testo' => [parent::class, 'testo', null],
        'valutazione' => [parent::class, 'valutazione', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
