<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EChef extends \EChef implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cellulare' => [parent::class, 'cellulare', null],
        "\0".parent::class."\0".'cognome' => [parent::class, 'cognome', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id_chef' => [parent::class, 'id_chef', null],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'ricette_pubblicate' => [parent::class, 'ricette_pubblicate', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'specializzazione' => [parent::class, 'specializzazione', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'cellulare' => [parent::class, 'cellulare', null],
        'cognome' => [parent::class, 'cognome', null],
        'email' => [parent::class, 'email', null],
        'id_chef' => [parent::class, 'id_chef', null],
        'nome' => [parent::class, 'nome', null],
        'password' => [parent::class, 'password', null],
        'ricette_pubblicate' => [parent::class, 'ricette_pubblicate', null],
        'roles' => [parent::class, 'roles', null],
        'specializzazione' => [parent::class, 'specializzazione', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
