<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ERicetta extends \ERicetta implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chef_ricetta' => [parent::class, 'chef_ricetta', null],
        "\0".parent::class."\0".'descrizione' => [parent::class, 'descrizione', null],
        "\0".parent::class."\0".'difficolta' => [parent::class, 'difficolta', null],
        "\0".parent::class."\0".'id_ricetta' => [parent::class, 'id_ricetta', null],
        "\0".parent::class."\0".'immagine' => [parent::class, 'immagine', null],
        "\0".parent::class."\0".'ingredienti' => [parent::class, 'ingredienti', null],
        "\0".parent::class."\0".'procedimento' => [parent::class, 'procedimento', null],
        "\0".parent::class."\0".'titolo' => [parent::class, 'titolo', null],
        'chef_ricetta' => [parent::class, 'chef_ricetta', null],
        'descrizione' => [parent::class, 'descrizione', null],
        'difficolta' => [parent::class, 'difficolta', null],
        'id_ricetta' => [parent::class, 'id_ricetta', null],
        'immagine' => [parent::class, 'immagine', null],
        'ingredienti' => [parent::class, 'ingredienti', null],
        'procedimento' => [parent::class, 'procedimento', null],
        'titolo' => [parent::class, 'titolo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
